// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJTN0wINgMoqrN9WEzn0TAMfwTlcD3JiA',
    appId: '1:802357399855:web:b4e1a5b5cdb68e1ca391da',
    messagingSenderId: '802357399855',
    projectId: 'shilpsetu-storefront',
    authDomain: 'shilpsetu-storefront.firebaseapp.com',
    storageBucket: 'shilpsetu-storefront.firebasestorage.app',
    measurementId: 'G-QPZY0YHB7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdv5pE7nUxWSrSmfR-3R62ATxC1J1-Xcw',
    appId: '1:802357399855:android:2d3394a461c0615ca391da',
    messagingSenderId: '802357399855',
    projectId: 'shilpsetu-storefront',
    storageBucket: 'shilpsetu-storefront.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9BMa7rNj7H4UbcYB00cHfQlNdIuMnmpQ',
    appId: '1:802357399855:ios:dd7af752a03e9e37a391da',
    messagingSenderId: '802357399855',
    projectId: 'shilpsetu-storefront',
    storageBucket: 'shilpsetu-storefront.firebasestorage.app',
    iosBundleId: 'com.example.s560226ApsFlutterShilpsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9BMa7rNj7H4UbcYB00cHfQlNdIuMnmpQ',
    appId: '1:802357399855:ios:dd7af752a03e9e37a391da',
    messagingSenderId: '802357399855',
    projectId: 'shilpsetu-storefront',
    storageBucket: 'shilpsetu-storefront.firebasestorage.app',
    iosBundleId: 'com.example.s560226ApsFlutterShilpsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJTN0wINgMoqrN9WEzn0TAMfwTlcD3JiA',
    appId: '1:802357399855:web:377594f8bf888e43a391da',
    messagingSenderId: '802357399855',
    projectId: 'shilpsetu-storefront',
    authDomain: 'shilpsetu-storefront.firebaseapp.com',
    storageBucket: 'shilpsetu-storefront.firebasestorage.app',
    measurementId: 'G-6DVGME2BZF',
  );
}
